// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/globalid_service.proto

package globalidservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGlobalIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalIDRequest) Reset() {
	*x = GetGlobalIDRequest{}
	mi := &file_proto_globalid_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalIDRequest) ProtoMessage() {}

func (x *GetGlobalIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_globalid_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalIDRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_globalid_service_proto_rawDescGZIP(), []int{0}
}

type GetGlobalIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalId      int64                  `protobuf:"varint,1,opt,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalIDResponse) Reset() {
	*x = GetGlobalIDResponse{}
	mi := &file_proto_globalid_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalIDResponse) ProtoMessage() {}

func (x *GetGlobalIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_globalid_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalIDResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_globalid_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetGlobalIDResponse) GetGlobalId() int64 {
	if x != nil {
		return x.GlobalId
	}
	return 0
}

type GetBatchGlobalIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchSize     int32                  `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchGlobalIDRequest) Reset() {
	*x = GetBatchGlobalIDRequest{}
	mi := &file_proto_globalid_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchGlobalIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchGlobalIDRequest) ProtoMessage() {}

func (x *GetBatchGlobalIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_globalid_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchGlobalIDRequest.ProtoReflect.Descriptor instead.
func (*GetBatchGlobalIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_globalid_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBatchGlobalIDRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type GetBatchGlobalIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalIds     []int64                `protobuf:"varint,1,rep,packed,name=global_ids,json=globalIds,proto3" json:"global_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchGlobalIDResponse) Reset() {
	*x = GetBatchGlobalIDResponse{}
	mi := &file_proto_globalid_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchGlobalIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchGlobalIDResponse) ProtoMessage() {}

func (x *GetBatchGlobalIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_globalid_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchGlobalIDResponse.ProtoReflect.Descriptor instead.
func (*GetBatchGlobalIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_globalid_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetBatchGlobalIDResponse) GetGlobalIds() []int64 {
	if x != nil {
		return x.GlobalIds
	}
	return nil
}

var File_proto_globalid_service_proto protoreflect.FileDescriptor

const file_proto_globalid_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/globalid_service.proto\x12\x0fglobalidservice\"\x14\n" +
	"\x12GetGlobalIDRequest\"2\n" +
	"\x13GetGlobalIDResponse\x12\x1b\n" +
	"\tglobal_id\x18\x01 \x01(\x03R\bglobalId\"8\n" +
	"\x17GetBatchGlobalIDRequest\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\x05R\tbatchSize\"9\n" +
	"\x18GetBatchGlobalIDResponse\x12\x1d\n" +
	"\n" +
	"global_ids\x18\x01 \x03(\x03R\tglobalIds2\xd4\x01\n" +
	"\x0fGlobalIDService\x12X\n" +
	"\vGetGlobalID\x12#.globalidservice.GetGlobalIDRequest\x1a$.globalidservice.GetGlobalIDResponse\x12g\n" +
	"\x10GetBatchGlobalID\x12(.globalidservice.GetBatchGlobalIDRequest\x1a).globalidservice.GetBatchGlobalIDResponseB<Z:github.com/quantara/globalid-service/proto;globalidserviceb\x06proto3"

var (
	file_proto_globalid_service_proto_rawDescOnce sync.Once
	file_proto_globalid_service_proto_rawDescData []byte
)

func file_proto_globalid_service_proto_rawDescGZIP() []byte {
	file_proto_globalid_service_proto_rawDescOnce.Do(func() {
		file_proto_globalid_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_globalid_service_proto_rawDesc), len(file_proto_globalid_service_proto_rawDesc)))
	})
	return file_proto_globalid_service_proto_rawDescData
}

var file_proto_globalid_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_globalid_service_proto_goTypes = []any{
	(*GetGlobalIDRequest)(nil),       // 0: globalidservice.GetGlobalIDRequest
	(*GetGlobalIDResponse)(nil),      // 1: globalidservice.GetGlobalIDResponse
	(*GetBatchGlobalIDRequest)(nil),  // 2: globalidservice.GetBatchGlobalIDRequest
	(*GetBatchGlobalIDResponse)(nil), // 3: globalidservice.GetBatchGlobalIDResponse
}
var file_proto_globalid_service_proto_depIdxs = []int32{
	0, // 0: globalidservice.GlobalIDService.GetGlobalID:input_type -> globalidservice.GetGlobalIDRequest
	2, // 1: globalidservice.GlobalIDService.GetBatchGlobalID:input_type -> globalidservice.GetBatchGlobalIDRequest
	1, // 2: globalidservice.GlobalIDService.GetGlobalID:output_type -> globalidservice.GetGlobalIDResponse
	3, // 3: globalidservice.GlobalIDService.GetBatchGlobalID:output_type -> globalidservice.GetBatchGlobalIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_globalid_service_proto_init() }
func file_proto_globalid_service_proto_init() {
	if File_proto_globalid_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_globalid_service_proto_rawDesc), len(file_proto_globalid_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_globalid_service_proto_goTypes,
		DependencyIndexes: file_proto_globalid_service_proto_depIdxs,
		MessageInfos:      file_proto_globalid_service_proto_msgTypes,
	}.Build()
	File_proto_globalid_service_proto = out.File
	file_proto_globalid_service_proto_goTypes = nil
	file_proto_globalid_service_proto_depIdxs = nil
}
