// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/globalid_service.proto

package globalidservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GlobalIDService_GetGlobalID_FullMethodName      = "/globalidservice.GlobalIDService/GetGlobalID"
	GlobalIDService_GetBatchGlobalID_FullMethodName = "/globalidservice.GlobalIDService/GetBatchGlobalID"
)

// GlobalIDServiceClient is the client API for GlobalIDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GlobalIDService provides unique GlobalID generation
type GlobalIDServiceClient interface {
	// GetGlobalID returns a single unique GlobalID
	GetGlobalID(ctx context.Context, in *GetGlobalIDRequest, opts ...grpc.CallOption) (*GetGlobalIDResponse, error)
	// GetBatchGlobalID returns a batch of unique GlobalIDs
	GetBatchGlobalID(ctx context.Context, in *GetBatchGlobalIDRequest, opts ...grpc.CallOption) (*GetBatchGlobalIDResponse, error)
}

type globalIDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGlobalIDServiceClient(cc grpc.ClientConnInterface) GlobalIDServiceClient {
	return &globalIDServiceClient{cc}
}

func (c *globalIDServiceClient) GetGlobalID(ctx context.Context, in *GetGlobalIDRequest, opts ...grpc.CallOption) (*GetGlobalIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalIDResponse)
	err := c.cc.Invoke(ctx, GlobalIDService_GetGlobalID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *globalIDServiceClient) GetBatchGlobalID(ctx context.Context, in *GetBatchGlobalIDRequest, opts ...grpc.CallOption) (*GetBatchGlobalIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchGlobalIDResponse)
	err := c.cc.Invoke(ctx, GlobalIDService_GetBatchGlobalID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlobalIDServiceServer is the server API for GlobalIDService service.
// All implementations must embed UnimplementedGlobalIDServiceServer
// for forward compatibility.
//
// GlobalIDService provides unique GlobalID generation
type GlobalIDServiceServer interface {
	// GetGlobalID returns a single unique GlobalID
	GetGlobalID(context.Context, *GetGlobalIDRequest) (*GetGlobalIDResponse, error)
	// GetBatchGlobalID returns a batch of unique GlobalIDs
	GetBatchGlobalID(context.Context, *GetBatchGlobalIDRequest) (*GetBatchGlobalIDResponse, error)
	mustEmbedUnimplementedGlobalIDServiceServer()
}

// UnimplementedGlobalIDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGlobalIDServiceServer struct{}

func (UnimplementedGlobalIDServiceServer) GetGlobalID(context.Context, *GetGlobalIDRequest) (*GetGlobalIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalID not implemented")
}
func (UnimplementedGlobalIDServiceServer) GetBatchGlobalID(context.Context, *GetBatchGlobalIDRequest) (*GetBatchGlobalIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBatchGlobalID not implemented")
}
func (UnimplementedGlobalIDServiceServer) mustEmbedUnimplementedGlobalIDServiceServer() {}
func (UnimplementedGlobalIDServiceServer) testEmbeddedByValue()                         {}

// UnsafeGlobalIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GlobalIDServiceServer will
// result in compilation errors.
type UnsafeGlobalIDServiceServer interface {
	mustEmbedUnimplementedGlobalIDServiceServer()
}

func RegisterGlobalIDServiceServer(s grpc.ServiceRegistrar, srv GlobalIDServiceServer) {
	// If the following call panics, it indicates UnimplementedGlobalIDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GlobalIDService_ServiceDesc, srv)
}

func _GlobalIDService_GetGlobalID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalIDServiceServer).GetGlobalID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlobalIDService_GetGlobalID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalIDServiceServer).GetGlobalID(ctx, req.(*GetGlobalIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlobalIDService_GetBatchGlobalID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchGlobalIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalIDServiceServer).GetBatchGlobalID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlobalIDService_GetBatchGlobalID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalIDServiceServer).GetBatchGlobalID(ctx, req.(*GetBatchGlobalIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GlobalIDService_ServiceDesc is the grpc.ServiceDesc for GlobalIDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GlobalIDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "globalidservice.GlobalIDService",
	HandlerType: (*GlobalIDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGlobalID",
			Handler:    _GlobalIDService_GetGlobalID_Handler,
		},
		{
			MethodName: "GetBatchGlobalID",
			Handler:    _GlobalIDService_GetBatchGlobalID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/globalid_service.proto",
}
