// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/id_service.proto

package idservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIDRequest) Reset() {
	*x = GetIDRequest{}
	mi := &file_proto_id_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIDRequest) ProtoMessage() {}

func (x *GetIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIDRequest.ProtoReflect.Descriptor instead.
func (*GetIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_id_service_proto_rawDescGZIP(), []int{0}
}

type GetIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIDResponse) Reset() {
	*x = GetIDResponse{}
	mi := &file_proto_id_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIDResponse) ProtoMessage() {}

func (x *GetIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIDResponse.ProtoReflect.Descriptor instead.
func (*GetIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_id_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetIDResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBatchIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchSize     int32                  `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchIDRequest) Reset() {
	*x = GetBatchIDRequest{}
	mi := &file_proto_id_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchIDRequest) ProtoMessage() {}

func (x *GetBatchIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchIDRequest.ProtoReflect.Descriptor instead.
func (*GetBatchIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_id_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBatchIDRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type GetBatchIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchIDResponse) Reset() {
	*x = GetBatchIDResponse{}
	mi := &file_proto_id_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchIDResponse) ProtoMessage() {}

func (x *GetBatchIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchIDResponse.ProtoReflect.Descriptor instead.
func (*GetBatchIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_id_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetBatchIDResponse) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_proto_id_service_proto protoreflect.FileDescriptor

const file_proto_id_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/id_service.proto\x12\tidservice\"\x0e\n" +
	"\fGetIDRequest\"\x1f\n" +
	"\rGetIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\x11GetBatchIDRequest\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\x05R\tbatchSize\"&\n" +
	"\x12GetBatchIDResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids2\x92\x01\n" +
	"\tIDService\x12:\n" +
	"\x05GetID\x12\x17.idservice.GetIDRequest\x1a\x18.idservice.GetIDResponse\x12I\n" +
	"\n" +
	"GetBatchID\x12\x1c.idservice.GetBatchIDRequest\x1a\x1d.idservice.GetBatchIDResponseB0Z.github.com/quantara/id-service/proto;idserviceb\x06proto3"

var (
	file_proto_id_service_proto_rawDescOnce sync.Once
	file_proto_id_service_proto_rawDescData []byte
)

func file_proto_id_service_proto_rawDescGZIP() []byte {
	file_proto_id_service_proto_rawDescOnce.Do(func() {
		file_proto_id_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_id_service_proto_rawDesc), len(file_proto_id_service_proto_rawDesc)))
	})
	return file_proto_id_service_proto_rawDescData
}

var file_proto_id_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_id_service_proto_goTypes = []any{
	(*GetIDRequest)(nil),       // 0: idservice.GetIDRequest
	(*GetIDResponse)(nil),      // 1: idservice.GetIDResponse
	(*GetBatchIDRequest)(nil),  // 2: idservice.GetBatchIDRequest
	(*GetBatchIDResponse)(nil), // 3: idservice.GetBatchIDResponse
}
var file_proto_id_service_proto_depIdxs = []int32{
	0, // 0: idservice.IDService.GetID:input_type -> idservice.GetIDRequest
	2, // 1: idservice.IDService.GetBatchID:input_type -> idservice.GetBatchIDRequest
	1, // 2: idservice.IDService.GetID:output_type -> idservice.GetIDResponse
	3, // 3: idservice.IDService.GetBatchID:output_type -> idservice.GetBatchIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_id_service_proto_init() }
func file_proto_id_service_proto_init() {
	if File_proto_id_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_id_service_proto_rawDesc), len(file_proto_id_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_id_service_proto_goTypes,
		DependencyIndexes: file_proto_id_service_proto_depIdxs,
		MessageInfos:      file_proto_id_service_proto_msgTypes,
	}.Build()
	File_proto_id_service_proto = out.File
	file_proto_id_service_proto_goTypes = nil
	file_proto_id_service_proto_depIdxs = nil
}
