// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/id_service.proto

package idservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IDService_GetID_FullMethodName      = "/idservice.IDService/GetID"
	IDService_GetBatchID_FullMethodName = "/idservice.IDService/GetBatchID"
)

// IDServiceClient is the client API for IDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IDService provides unique ID generation
type IDServiceClient interface {
	// GetID returns a single unique ID
	GetID(ctx context.Context, in *GetIDRequest, opts ...grpc.CallOption) (*GetIDResponse, error)
	// GetBatchID returns a batch of unique IDs
	GetBatchID(ctx context.Context, in *GetBatchIDRequest, opts ...grpc.CallOption) (*GetBatchIDResponse, error)
}

type iDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIDServiceClient(cc grpc.ClientConnInterface) IDServiceClient {
	return &iDServiceClient{cc}
}

func (c *iDServiceClient) GetID(ctx context.Context, in *GetIDRequest, opts ...grpc.CallOption) (*GetIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIDResponse)
	err := c.cc.Invoke(ctx, IDService_GetID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDServiceClient) GetBatchID(ctx context.Context, in *GetBatchIDRequest, opts ...grpc.CallOption) (*GetBatchIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchIDResponse)
	err := c.cc.Invoke(ctx, IDService_GetBatchID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDServiceServer is the server API for IDService service.
// All implementations must embed UnimplementedIDServiceServer
// for forward compatibility.
//
// IDService provides unique ID generation
type IDServiceServer interface {
	// GetID returns a single unique ID
	GetID(context.Context, *GetIDRequest) (*GetIDResponse, error)
	// GetBatchID returns a batch of unique IDs
	GetBatchID(context.Context, *GetBatchIDRequest) (*GetBatchIDResponse, error)
	mustEmbedUnimplementedIDServiceServer()
}

// UnimplementedIDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIDServiceServer struct{}

func (UnimplementedIDServiceServer) GetID(context.Context, *GetIDRequest) (*GetIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetID not implemented")
}
func (UnimplementedIDServiceServer) GetBatchID(context.Context, *GetBatchIDRequest) (*GetBatchIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBatchID not implemented")
}
func (UnimplementedIDServiceServer) mustEmbedUnimplementedIDServiceServer() {}
func (UnimplementedIDServiceServer) testEmbeddedByValue()                   {}

// UnsafeIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDServiceServer will
// result in compilation errors.
type UnsafeIDServiceServer interface {
	mustEmbedUnimplementedIDServiceServer()
}

func RegisterIDServiceServer(s grpc.ServiceRegistrar, srv IDServiceServer) {
	// If the following call panics, it indicates UnimplementedIDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IDService_ServiceDesc, srv)
}

func _IDService_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServiceServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDService_GetID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServiceServer).GetID(ctx, req.(*GetIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDService_GetBatchID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServiceServer).GetBatchID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDService_GetBatchID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServiceServer).GetBatchID(ctx, req.(*GetBatchIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IDService_ServiceDesc is the grpc.ServiceDesc for IDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idservice.IDService",
	HandlerType: (*IDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetID",
			Handler:    _IDService_GetID_Handler,
		},
		{
			MethodName: "GetBatchID",
			Handler:    _IDService_GetBatchID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/id_service.proto",
}
