server:
  port: 8089

spring:
  application:
    name: enricher-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions
    username: postgres
    password: postgres123
  data:
    redis:
      timeout: 5000
      cluster:
        nodes: localhost:6379

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    tags:
      application: enricher-service

enricher:
  search-service:
    base-url: http://localhost:8081
  metadata:
    url: http://localhost:8083/api/search-service/metadata/v2
    local-file: ""
