// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: search_service.proto

package searchservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchService_GetObjectRevisionById_FullMethodName         = "/searchservice.SearchService/GetObjectRevisionById"
	SearchService_GetObjectByGlobalId_FullMethodName           = "/searchservice.SearchService/GetObjectByGlobalId"
	SearchService_GetObjectCollectionByParentId_FullMethodName = "/searchservice.SearchService/GetObjectCollectionByParentId"
	SearchService_GetObjectGlobalIdByAltId_FullMethodName      = "/searchservice.SearchService/GetObjectGlobalIdByAltId"
	SearchService_GetObjectCollectionByFilter_FullMethodName   = "/searchservice.SearchService/GetObjectCollectionByFilter"
	SearchService_GetDomainConfig_FullMethodName               = "/searchservice.SearchService/GetDomainConfig"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	GetObjectRevisionById(ctx context.Context, in *GetObjectRevisionByIdRequest, opts ...grpc.CallOption) (*GetObjectRevisionByIdResponse, error)
	GetObjectByGlobalId(ctx context.Context, in *GetObjectByGlobalIdRequest, opts ...grpc.CallOption) (*GetObjectByGlobalIdResponse, error)
	GetObjectCollectionByParentId(ctx context.Context, in *GetObjectCollectionByParentIdRequest, opts ...grpc.CallOption) (*GetObjectCollectionByParentIdResponse, error)
	GetObjectGlobalIdByAltId(ctx context.Context, in *GetObjectGlobalIdByAltIdRequest, opts ...grpc.CallOption) (*GetObjectGlobalIdByAltIdResponse, error)
	GetObjectCollectionByFilter(ctx context.Context, in *GetObjectCollectionByFilterRequest, opts ...grpc.CallOption) (*GetObjectCollectionByFilterResponse, error)
	GetDomainConfig(ctx context.Context, in *GetDomainConfigRequest, opts ...grpc.CallOption) (*GetDomainConfigResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) GetObjectRevisionById(ctx context.Context, in *GetObjectRevisionByIdRequest, opts ...grpc.CallOption) (*GetObjectRevisionByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectRevisionByIdResponse)
	err := c.cc.Invoke(ctx, SearchService_GetObjectRevisionById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetObjectByGlobalId(ctx context.Context, in *GetObjectByGlobalIdRequest, opts ...grpc.CallOption) (*GetObjectByGlobalIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectByGlobalIdResponse)
	err := c.cc.Invoke(ctx, SearchService_GetObjectByGlobalId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetObjectCollectionByParentId(ctx context.Context, in *GetObjectCollectionByParentIdRequest, opts ...grpc.CallOption) (*GetObjectCollectionByParentIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectCollectionByParentIdResponse)
	err := c.cc.Invoke(ctx, SearchService_GetObjectCollectionByParentId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetObjectGlobalIdByAltId(ctx context.Context, in *GetObjectGlobalIdByAltIdRequest, opts ...grpc.CallOption) (*GetObjectGlobalIdByAltIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectGlobalIdByAltIdResponse)
	err := c.cc.Invoke(ctx, SearchService_GetObjectGlobalIdByAltId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetObjectCollectionByFilter(ctx context.Context, in *GetObjectCollectionByFilterRequest, opts ...grpc.CallOption) (*GetObjectCollectionByFilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectCollectionByFilterResponse)
	err := c.cc.Invoke(ctx, SearchService_GetObjectCollectionByFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetDomainConfig(ctx context.Context, in *GetDomainConfigRequest, opts ...grpc.CallOption) (*GetDomainConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDomainConfigResponse)
	err := c.cc.Invoke(ctx, SearchService_GetDomainConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
type SearchServiceServer interface {
	GetObjectRevisionById(context.Context, *GetObjectRevisionByIdRequest) (*GetObjectRevisionByIdResponse, error)
	GetObjectByGlobalId(context.Context, *GetObjectByGlobalIdRequest) (*GetObjectByGlobalIdResponse, error)
	GetObjectCollectionByParentId(context.Context, *GetObjectCollectionByParentIdRequest) (*GetObjectCollectionByParentIdResponse, error)
	GetObjectGlobalIdByAltId(context.Context, *GetObjectGlobalIdByAltIdRequest) (*GetObjectGlobalIdByAltIdResponse, error)
	GetObjectCollectionByFilter(context.Context, *GetObjectCollectionByFilterRequest) (*GetObjectCollectionByFilterResponse, error)
	GetDomainConfig(context.Context, *GetDomainConfigRequest) (*GetDomainConfigResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) GetObjectRevisionById(context.Context, *GetObjectRevisionByIdRequest) (*GetObjectRevisionByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectRevisionById not implemented")
}
func (UnimplementedSearchServiceServer) GetObjectByGlobalId(context.Context, *GetObjectByGlobalIdRequest) (*GetObjectByGlobalIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectByGlobalId not implemented")
}
func (UnimplementedSearchServiceServer) GetObjectCollectionByParentId(context.Context, *GetObjectCollectionByParentIdRequest) (*GetObjectCollectionByParentIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectCollectionByParentId not implemented")
}
func (UnimplementedSearchServiceServer) GetObjectGlobalIdByAltId(context.Context, *GetObjectGlobalIdByAltIdRequest) (*GetObjectGlobalIdByAltIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectGlobalIdByAltId not implemented")
}
func (UnimplementedSearchServiceServer) GetObjectCollectionByFilter(context.Context, *GetObjectCollectionByFilterRequest) (*GetObjectCollectionByFilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectCollectionByFilter not implemented")
}
func (UnimplementedSearchServiceServer) GetDomainConfig(context.Context, *GetDomainConfigRequest) (*GetDomainConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDomainConfig not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_GetObjectRevisionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRevisionByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetObjectRevisionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetObjectRevisionById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetObjectRevisionById(ctx, req.(*GetObjectRevisionByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetObjectByGlobalId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectByGlobalIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetObjectByGlobalId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetObjectByGlobalId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetObjectByGlobalId(ctx, req.(*GetObjectByGlobalIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetObjectCollectionByParentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectCollectionByParentIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetObjectCollectionByParentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetObjectCollectionByParentId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetObjectCollectionByParentId(ctx, req.(*GetObjectCollectionByParentIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetObjectGlobalIdByAltId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectGlobalIdByAltIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetObjectGlobalIdByAltId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetObjectGlobalIdByAltId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetObjectGlobalIdByAltId(ctx, req.(*GetObjectGlobalIdByAltIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetObjectCollectionByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectCollectionByFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetObjectCollectionByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetObjectCollectionByFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetObjectCollectionByFilter(ctx, req.(*GetObjectCollectionByFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetDomainConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetDomainConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetDomainConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetDomainConfig(ctx, req.(*GetDomainConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "searchservice.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetObjectRevisionById",
			Handler:    _SearchService_GetObjectRevisionById_Handler,
		},
		{
			MethodName: "GetObjectByGlobalId",
			Handler:    _SearchService_GetObjectByGlobalId_Handler,
		},
		{
			MethodName: "GetObjectCollectionByParentId",
			Handler:    _SearchService_GetObjectCollectionByParentId_Handler,
		},
		{
			MethodName: "GetObjectGlobalIdByAltId",
			Handler:    _SearchService_GetObjectGlobalIdByAltId_Handler,
		},
		{
			MethodName: "GetObjectCollectionByFilter",
			Handler:    _SearchService_GetObjectCollectionByFilter_Handler,
		},
		{
			MethodName: "GetDomainConfig",
			Handler:    _SearchService_GetDomainConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search_service.proto",
}
