// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: transaction_service.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginTxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimeoutSeconds *int32                 `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3,oneof" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BeginTxRequest) Reset() {
	*x = BeginTxRequest{}
	mi := &file_transaction_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTxRequest) ProtoMessage() {}

func (x *BeginTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTxRequest.ProtoReflect.Descriptor instead.
func (*BeginTxRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{0}
}

func (x *BeginTxRequest) GetTimeoutSeconds() int32 {
	if x != nil && x.TimeoutSeconds != nil {
		return *x.TimeoutSeconds
	}
	return 0
}

type BeginTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTxResponse) Reset() {
	*x = BeginTxResponse{}
	mi := &file_transaction_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTxResponse) ProtoMessage() {}

func (x *BeginTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTxResponse.ProtoReflect.Descriptor instead.
func (*BeginTxResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{1}
}

func (x *BeginTxResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type ObjectHeaders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GlobalId      int64                  `protobuf:"varint,2,opt,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	ObjectType    string                 `protobuf:"bytes,3,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	LockId        string                 `protobuf:"bytes,4,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Revision      int32                  `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Version       *int32                 `protobuf:"varint,6,opt,name=version,proto3,oneof" json:"version,omitempty"`
	ActualFrom    *string                `protobuf:"bytes,7,opt,name=actual_from,json=actualFrom,proto3,oneof" json:"actual_from,omitempty"`
	DraftStatus   *string                `protobuf:"bytes,8,opt,name=draft_status,json=draftStatus,proto3,oneof" json:"draft_status,omitempty"`
	ParentId      *int64                 `protobuf:"varint,9,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectHeaders) Reset() {
	*x = ObjectHeaders{}
	mi := &file_transaction_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectHeaders) ProtoMessage() {}

func (x *ObjectHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectHeaders.ProtoReflect.Descriptor instead.
func (*ObjectHeaders) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectHeaders) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ObjectHeaders) GetGlobalId() int64 {
	if x != nil {
		return x.GlobalId
	}
	return 0
}

func (x *ObjectHeaders) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ObjectHeaders) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *ObjectHeaders) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ObjectHeaders) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *ObjectHeaders) GetActualFrom() string {
	if x != nil && x.ActualFrom != nil {
		return *x.ActualFrom
	}
	return ""
}

func (x *ObjectHeaders) GetDraftStatus() string {
	if x != nil && x.DraftStatus != nil {
		return *x.DraftStatus
	}
	return ""
}

func (x *ObjectHeaders) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type SaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Headers       *ObjectHeaders         `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	AlgorithmId   *uint32                `protobuf:"varint,4,opt,name=algorithm_id,json=algorithmId,proto3,oneof" json:"algorithm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_transaction_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{3}
}

func (x *SaveRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *SaveRequest) GetHeaders() *ObjectHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SaveRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SaveRequest) GetAlgorithmId() uint32 {
	if x != nil && x.AlgorithmId != nil {
		return *x.AlgorithmId
	}
	return 0
}

type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_transaction_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{4}
}

func (x *SaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_transaction_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{5}
}

func (x *CommitRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ObjectsSaved  int32                  `protobuf:"varint,3,opt,name=objects_saved,json=objectsSaved,proto3" json:"objects_saved,omitempty"`
	Results       []*ObjectResult        `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_transaction_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{6}
}

func (x *CommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommitResponse) GetObjectsSaved() int32 {
	if x != nil {
		return x.ObjectsSaved
	}
	return 0
}

func (x *CommitResponse) GetResults() []*ObjectResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ObjectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectResult) Reset() {
	*x = ObjectResult{}
	mi := &file_transaction_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectResult) ProtoMessage() {}

func (x *ObjectResult) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectResult.ProtoReflect.Descriptor instead.
func (*ObjectResult) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ObjectResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ObjectResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_transaction_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{8}
}

func (x *RollbackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_transaction_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{9}
}

func (x *RollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_transaction_service_proto protoreflect.FileDescriptor

const file_transaction_service_proto_rawDesc = "" +
	"\n" +
	"\x19transaction_service.proto\x12\vtransaction\"R\n" +
	"\x0eBeginTxRequest\x12,\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x05H\x00R\x0etimeoutSeconds\x88\x01\x01B\x12\n" +
	"\x10_timeout_seconds\"8\n" +
	"\x0fBeginTxResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\xdc\x02\n" +
	"\rObjectHeaders\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tglobal_id\x18\x02 \x01(\x03R\bglobalId\x12\x1f\n" +
	"\vobject_type\x18\x03 \x01(\tR\n" +
	"objectType\x12\x17\n" +
	"\alock_id\x18\x04 \x01(\tR\x06lockId\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x05R\brevision\x12\x1d\n" +
	"\aversion\x18\x06 \x01(\x05H\x00R\aversion\x88\x01\x01\x12$\n" +
	"\vactual_from\x18\a \x01(\tH\x01R\n" +
	"actualFrom\x88\x01\x01\x12&\n" +
	"\fdraft_status\x18\b \x01(\tH\x02R\vdraftStatus\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\t \x01(\x03H\x03R\bparentId\x88\x01\x01B\n" +
	"\n" +
	"\b_versionB\x0e\n" +
	"\f_actual_fromB\x0f\n" +
	"\r_draft_statusB\f\n" +
	"\n" +
	"_parent_id\"\xbd\x01\n" +
	"\vSaveRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x124\n" +
	"\aheaders\x18\x02 \x01(\v2\x1a.transaction.ObjectHeadersR\aheaders\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12&\n" +
	"\falgorithm_id\x18\x04 \x01(\rH\x00R\valgorithmId\x88\x01\x01B\x0f\n" +
	"\r_algorithm_id\">\n" +
	"\fSaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"6\n" +
	"\rCommitRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\x9a\x01\n" +
	"\x0eCommitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\robjects_saved\x18\x03 \x01(\x05R\fobjectsSaved\x123\n" +
	"\aresults\x18\x04 \x03(\v2\x19.transaction.ObjectResultR\aresults\"N\n" +
	"\fObjectResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"8\n" +
	"\x0fRollbackRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\",\n" +
	"\x10RollbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf3\x02\n" +
	"\x12TransactionService\x12M\n" +
	"\x10BeginTransaction\x12\x1b.transaction.BeginTxRequest\x1a\x1c.transaction.BeginTxResponse\x12;\n" +
	"\x04Save\x12\x18.transaction.SaveRequest\x1a\x19.transaction.SaveResponse\x12E\n" +
	"\n" +
	"SaveStream\x12\x18.transaction.SaveRequest\x1a\x19.transaction.SaveResponse(\x010\x01\x12A\n" +
	"\x06Commit\x12\x1a.transaction.CommitRequest\x1a\x1b.transaction.CommitResponse\x12G\n" +
	"\bRollback\x12\x1c.transaction.RollbackRequest\x1a\x1d.transaction.RollbackResponseB8Z6github.com/quantara/object-framework/proto/transactionb\x06proto3"

var (
	file_transaction_service_proto_rawDescOnce sync.Once
	file_transaction_service_proto_rawDescData []byte
)

func file_transaction_service_proto_rawDescGZIP() []byte {
	file_transaction_service_proto_rawDescOnce.Do(func() {
		file_transaction_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_service_proto_rawDesc), len(file_transaction_service_proto_rawDesc)))
	})
	return file_transaction_service_proto_rawDescData
}

var file_transaction_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_transaction_service_proto_goTypes = []any{
	(*BeginTxRequest)(nil),   // 0: transaction.BeginTxRequest
	(*BeginTxResponse)(nil),  // 1: transaction.BeginTxResponse
	(*ObjectHeaders)(nil),    // 2: transaction.ObjectHeaders
	(*SaveRequest)(nil),      // 3: transaction.SaveRequest
	(*SaveResponse)(nil),     // 4: transaction.SaveResponse
	(*CommitRequest)(nil),    // 5: transaction.CommitRequest
	(*CommitResponse)(nil),   // 6: transaction.CommitResponse
	(*ObjectResult)(nil),     // 7: transaction.ObjectResult
	(*RollbackRequest)(nil),  // 8: transaction.RollbackRequest
	(*RollbackResponse)(nil), // 9: transaction.RollbackResponse
}
var file_transaction_service_proto_depIdxs = []int32{
	2, // 0: transaction.SaveRequest.headers:type_name -> transaction.ObjectHeaders
	7, // 1: transaction.CommitResponse.results:type_name -> transaction.ObjectResult
	0, // 2: transaction.TransactionService.BeginTransaction:input_type -> transaction.BeginTxRequest
	3, // 3: transaction.TransactionService.Save:input_type -> transaction.SaveRequest
	3, // 4: transaction.TransactionService.SaveStream:input_type -> transaction.SaveRequest
	5, // 5: transaction.TransactionService.Commit:input_type -> transaction.CommitRequest
	8, // 6: transaction.TransactionService.Rollback:input_type -> transaction.RollbackRequest
	1, // 7: transaction.TransactionService.BeginTransaction:output_type -> transaction.BeginTxResponse
	4, // 8: transaction.TransactionService.Save:output_type -> transaction.SaveResponse
	4, // 9: transaction.TransactionService.SaveStream:output_type -> transaction.SaveResponse
	6, // 10: transaction.TransactionService.Commit:output_type -> transaction.CommitResponse
	9, // 11: transaction.TransactionService.Rollback:output_type -> transaction.RollbackResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_service_proto_init() }
func file_transaction_service_proto_init() {
	if File_transaction_service_proto != nil {
		return
	}
	file_transaction_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_transaction_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_transaction_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_service_proto_rawDesc), len(file_transaction_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_service_proto_goTypes,
		DependencyIndexes: file_transaction_service_proto_depIdxs,
		MessageInfos:      file_transaction_service_proto_msgTypes,
	}.Build()
	File_transaction_service_proto = out.File
	file_transaction_service_proto_goTypes = nil
	file_transaction_service_proto_depIdxs = nil
}
