// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: lock_service.proto

package lockservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockStatus int32

const (
	LockStatus_LOCK_STATUS_UNSPECIFIED LockStatus = 0
	LockStatus_LOCK_STATUS_FREE        LockStatus = 1
	LockStatus_LOCK_STATUS_ACQUIRED    LockStatus = 2
)

// Enum value maps for LockStatus.
var (
	LockStatus_name = map[int32]string{
		0: "LOCK_STATUS_UNSPECIFIED",
		1: "LOCK_STATUS_FREE",
		2: "LOCK_STATUS_ACQUIRED",
	}
	LockStatus_value = map[string]int32{
		"LOCK_STATUS_UNSPECIFIED": 0,
		"LOCK_STATUS_FREE":        1,
		"LOCK_STATUS_ACQUIRED":    2,
	}
)

func (x LockStatus) Enum() *LockStatus {
	p := new(LockStatus)
	*p = x
	return p
}

func (x LockStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lock_service_proto_enumTypes[0].Descriptor()
}

func (LockStatus) Type() protoreflect.EnumType {
	return &file_lock_service_proto_enumTypes[0]
}

func (x LockStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockStatus.Descriptor instead.
func (LockStatus) EnumDescriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{0}
}

type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalId      int64                  `protobuf:"varint,1,opt,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_lock_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{0}
}

func (x *LockRequest) GetGlobalId() int64 {
	if x != nil {
		return x.GlobalId
	}
	return 0
}

type LockWithTTLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalId      int64                  `protobuf:"varint,1,opt,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	TtlMs         int64                  `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockWithTTLRequest) Reset() {
	*x = LockWithTTLRequest{}
	mi := &file_lock_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockWithTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockWithTTLRequest) ProtoMessage() {}

func (x *LockWithTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockWithTTLRequest.ProtoReflect.Descriptor instead.
func (*LockWithTTLRequest) Descriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{1}
}

func (x *LockWithTTLRequest) GetGlobalId() int64 {
	if x != nil {
		return x.GlobalId
	}
	return 0
}

func (x *LockWithTTLRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_lock_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{2}
}

func (x *LockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LockResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LockResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *LockResponse) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalId      int64                  `protobuf:"varint,1,opt,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	TtlMs         int64                  `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_lock_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{3}
}

func (x *RenewRequest) GetGlobalId() int64 {
	if x != nil {
		return x.GlobalId
	}
	return 0
}

func (x *RenewRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RenewRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_lock_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{4}
}

func (x *RenewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenewResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RenewResponse) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type CheckLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalId      int64                  `protobuf:"varint,1,opt,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLockRequest) Reset() {
	*x = CheckLockRequest{}
	mi := &file_lock_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLockRequest) ProtoMessage() {}

func (x *CheckLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLockRequest.ProtoReflect.Descriptor instead.
func (*CheckLockRequest) Descriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckLockRequest) GetGlobalId() int64 {
	if x != nil {
		return x.GlobalId
	}
	return 0
}

type CheckLockByTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalId      int64                  `protobuf:"varint,1,opt,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLockByTokenRequest) Reset() {
	*x = CheckLockByTokenRequest{}
	mi := &file_lock_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLockByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLockByTokenRequest) ProtoMessage() {}

func (x *CheckLockByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLockByTokenRequest.ProtoReflect.Descriptor instead.
func (*CheckLockByTokenRequest) Descriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{6}
}

func (x *CheckLockByTokenRequest) GetGlobalId() int64 {
	if x != nil {
		return x.GlobalId
	}
	return 0
}

func (x *CheckLockByTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CheckLockResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Exists         bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Status         LockStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=lockservice.LockStatus" json:"status,omitempty"`
	Token          string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	ExpireAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	TtlRemainingMs int64                  `protobuf:"varint,5,opt,name=ttl_remaining_ms,json=ttlRemainingMs,proto3" json:"ttl_remaining_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckLockResponse) Reset() {
	*x = CheckLockResponse{}
	mi := &file_lock_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLockResponse) ProtoMessage() {}

func (x *CheckLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLockResponse.ProtoReflect.Descriptor instead.
func (*CheckLockResponse) Descriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{7}
}

func (x *CheckLockResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckLockResponse) GetStatus() LockStatus {
	if x != nil {
		return x.Status
	}
	return LockStatus_LOCK_STATUS_UNSPECIFIED
}

func (x *CheckLockResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckLockResponse) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *CheckLockResponse) GetTtlRemainingMs() int64 {
	if x != nil {
		return x.TtlRemainingMs
	}
	return 0
}

type UnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalId      int64                  `protobuf:"varint,1,opt,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_lock_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{8}
}

func (x *UnlockRequest) GetGlobalId() int64 {
	if x != nil {
		return x.GlobalId
	}
	return 0
}

func (x *UnlockRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResponse) Reset() {
	*x = UnlockResponse{}
	mi := &file_lock_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResponse) ProtoMessage() {}

func (x *UnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResponse.ProtoReflect.Descriptor instead.
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return file_lock_service_proto_rawDescGZIP(), []int{9}
}

func (x *UnlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlockResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_lock_service_proto protoreflect.FileDescriptor

const file_lock_service_proto_rawDesc = "" +
	"\n" +
	"\x12lock_service.proto\x12\vlockservice\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\vLockRequest\x12\x1b\n" +
	"\tglobal_id\x18\x01 \x01(\x03R\bglobalId\"H\n" +
	"\x12LockWithTTLRequest\x12\x1b\n" +
	"\tglobal_id\x18\x01 \x01(\x03R\bglobalId\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x03R\x05ttlMs\"\x9c\x01\n" +
	"\fLockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x127\n" +
	"\texpire_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"X\n" +
	"\fRenewRequest\x12\x1b\n" +
	"\tglobal_id\x18\x01 \x01(\x03R\bglobalId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\x03R\x05ttlMs\"\x87\x01\n" +
	"\rRenewResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x127\n" +
	"\texpire_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"/\n" +
	"\x10CheckLockRequest\x12\x1b\n" +
	"\tglobal_id\x18\x01 \x01(\x03R\bglobalId\"L\n" +
	"\x17CheckLockByTokenRequest\x12\x1b\n" +
	"\tglobal_id\x18\x01 \x01(\x03R\bglobalId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\xd5\x01\n" +
	"\x11CheckLockResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.lockservice.LockStatusR\x06status\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x127\n" +
	"\texpire_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x12(\n" +
	"\x10ttl_remaining_ms\x18\x05 \x01(\x03R\x0ettlRemainingMs\"B\n" +
	"\rUnlockRequest\x12\x1b\n" +
	"\tglobal_id\x18\x01 \x01(\x03R\bglobalId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"O\n" +
	"\x0eUnlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage*Y\n" +
	"\n" +
	"LockStatus\x12\x1b\n" +
	"\x17LOCK_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10LOCK_STATUS_FREE\x10\x01\x12\x18\n" +
	"\x14LOCK_STATUS_ACQUIRED\x10\x022\xbe\x03\n" +
	"\vLockService\x12;\n" +
	"\x04Lock\x12\x18.lockservice.LockRequest\x1a\x19.lockservice.LockResponse\x12I\n" +
	"\vLockWithTTL\x12\x1f.lockservice.LockWithTTLRequest\x1a\x19.lockservice.LockResponse\x12>\n" +
	"\x05Renew\x12\x19.lockservice.RenewRequest\x1a\x1a.lockservice.RenewResponse\x12J\n" +
	"\tCheckLock\x12\x1d.lockservice.CheckLockRequest\x1a\x1e.lockservice.CheckLockResponse\x12X\n" +
	"\x10CheckLockByToken\x12$.lockservice.CheckLockByTokenRequest\x1a\x1e.lockservice.CheckLockResponse\x12A\n" +
	"\x06Unlock\x12\x1a.lockservice.UnlockRequest\x1a\x1b.lockservice.UnlockResponseB8Z6github.com/quantara/object-framework/proto/lockserviceb\x06proto3"

var (
	file_lock_service_proto_rawDescOnce sync.Once
	file_lock_service_proto_rawDescData []byte
)

func file_lock_service_proto_rawDescGZIP() []byte {
	file_lock_service_proto_rawDescOnce.Do(func() {
		file_lock_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lock_service_proto_rawDesc), len(file_lock_service_proto_rawDesc)))
	})
	return file_lock_service_proto_rawDescData
}

var file_lock_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lock_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_lock_service_proto_goTypes = []any{
	(LockStatus)(0),                 // 0: lockservice.LockStatus
	(*LockRequest)(nil),             // 1: lockservice.LockRequest
	(*LockWithTTLRequest)(nil),      // 2: lockservice.LockWithTTLRequest
	(*LockResponse)(nil),            // 3: lockservice.LockResponse
	(*RenewRequest)(nil),            // 4: lockservice.RenewRequest
	(*RenewResponse)(nil),           // 5: lockservice.RenewResponse
	(*CheckLockRequest)(nil),        // 6: lockservice.CheckLockRequest
	(*CheckLockByTokenRequest)(nil), // 7: lockservice.CheckLockByTokenRequest
	(*CheckLockResponse)(nil),       // 8: lockservice.CheckLockResponse
	(*UnlockRequest)(nil),           // 9: lockservice.UnlockRequest
	(*UnlockResponse)(nil),          // 10: lockservice.UnlockResponse
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_lock_service_proto_depIdxs = []int32{
	11, // 0: lockservice.LockResponse.expire_at:type_name -> google.protobuf.Timestamp
	11, // 1: lockservice.RenewResponse.expire_at:type_name -> google.protobuf.Timestamp
	0,  // 2: lockservice.CheckLockResponse.status:type_name -> lockservice.LockStatus
	11, // 3: lockservice.CheckLockResponse.expire_at:type_name -> google.protobuf.Timestamp
	1,  // 4: lockservice.LockService.Lock:input_type -> lockservice.LockRequest
	2,  // 5: lockservice.LockService.LockWithTTL:input_type -> lockservice.LockWithTTLRequest
	4,  // 6: lockservice.LockService.Renew:input_type -> lockservice.RenewRequest
	6,  // 7: lockservice.LockService.CheckLock:input_type -> lockservice.CheckLockRequest
	7,  // 8: lockservice.LockService.CheckLockByToken:input_type -> lockservice.CheckLockByTokenRequest
	9,  // 9: lockservice.LockService.Unlock:input_type -> lockservice.UnlockRequest
	3,  // 10: lockservice.LockService.Lock:output_type -> lockservice.LockResponse
	3,  // 11: lockservice.LockService.LockWithTTL:output_type -> lockservice.LockResponse
	5,  // 12: lockservice.LockService.Renew:output_type -> lockservice.RenewResponse
	8,  // 13: lockservice.LockService.CheckLock:output_type -> lockservice.CheckLockResponse
	8,  // 14: lockservice.LockService.CheckLockByToken:output_type -> lockservice.CheckLockResponse
	10, // 15: lockservice.LockService.Unlock:output_type -> lockservice.UnlockResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_lock_service_proto_init() }
func file_lock_service_proto_init() {
	if File_lock_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lock_service_proto_rawDesc), len(file_lock_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lock_service_proto_goTypes,
		DependencyIndexes: file_lock_service_proto_depIdxs,
		EnumInfos:         file_lock_service_proto_enumTypes,
		MessageInfos:      file_lock_service_proto_msgTypes,
	}.Build()
	File_lock_service_proto = out.File
	file_lock_service_proto_goTypes = nil
	file_lock_service_proto_depIdxs = nil
}
