// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: proto/search_service.proto

package searchservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortDirection int32

const (
	SortDirection_SORT_DIRECTION_UNSPECIFIED SortDirection = 0
	SortDirection_SORT_DIRECTION_ASC         SortDirection = 1
	SortDirection_SORT_DIRECTION_DESC        SortDirection = 2
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_UNSPECIFIED",
		1: "SORT_DIRECTION_ASC",
		2: "SORT_DIRECTION_DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_DIRECTION_UNSPECIFIED": 0,
		"SORT_DIRECTION_ASC":         1,
		"SORT_DIRECTION_DESC":        2,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_search_service_proto_enumTypes[0].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_proto_search_service_proto_enumTypes[0]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{0}
}

type FilterOperator int32

const (
	FilterOperator_FILTER_OPERATOR_UNSPECIFIED FilterOperator = 0
	FilterOperator_FILTER_OPERATOR_EQ          FilterOperator = 1
	FilterOperator_FILTER_OPERATOR_NE          FilterOperator = 2
	FilterOperator_FILTER_OPERATOR_GT          FilterOperator = 3
	FilterOperator_FILTER_OPERATOR_GE          FilterOperator = 4
	FilterOperator_FILTER_OPERATOR_LT          FilterOperator = 5
	FilterOperator_FILTER_OPERATOR_LE          FilterOperator = 6
	FilterOperator_FILTER_OPERATOR_IN          FilterOperator = 7
	FilterOperator_FILTER_OPERATOR_NOT_IN      FilterOperator = 8
	FilterOperator_FILTER_OPERATOR_LIKE        FilterOperator = 9
	FilterOperator_FILTER_OPERATOR_IS_NULL     FilterOperator = 10
	FilterOperator_FILTER_OPERATOR_IS_NOT_NULL FilterOperator = 11
)

// Enum value maps for FilterOperator.
var (
	FilterOperator_name = map[int32]string{
		0:  "FILTER_OPERATOR_UNSPECIFIED",
		1:  "FILTER_OPERATOR_EQ",
		2:  "FILTER_OPERATOR_NE",
		3:  "FILTER_OPERATOR_GT",
		4:  "FILTER_OPERATOR_GE",
		5:  "FILTER_OPERATOR_LT",
		6:  "FILTER_OPERATOR_LE",
		7:  "FILTER_OPERATOR_IN",
		8:  "FILTER_OPERATOR_NOT_IN",
		9:  "FILTER_OPERATOR_LIKE",
		10: "FILTER_OPERATOR_IS_NULL",
		11: "FILTER_OPERATOR_IS_NOT_NULL",
	}
	FilterOperator_value = map[string]int32{
		"FILTER_OPERATOR_UNSPECIFIED": 0,
		"FILTER_OPERATOR_EQ":          1,
		"FILTER_OPERATOR_NE":          2,
		"FILTER_OPERATOR_GT":          3,
		"FILTER_OPERATOR_GE":          4,
		"FILTER_OPERATOR_LT":          5,
		"FILTER_OPERATOR_LE":          6,
		"FILTER_OPERATOR_IN":          7,
		"FILTER_OPERATOR_NOT_IN":      8,
		"FILTER_OPERATOR_LIKE":        9,
		"FILTER_OPERATOR_IS_NULL":     10,
		"FILTER_OPERATOR_IS_NOT_NULL": 11,
	}
)

func (x FilterOperator) Enum() *FilterOperator {
	p := new(FilterOperator)
	*p = x
	return p
}

func (x FilterOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_search_service_proto_enumTypes[1].Descriptor()
}

func (FilterOperator) Type() protoreflect.EnumType {
	return &file_proto_search_service_proto_enumTypes[1]
}

func (x FilterOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOperator.Descriptor instead.
func (FilterOperator) EnumDescriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{1}
}

type GetObjectRevisionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectClass   string                 `protobuf:"bytes,1,opt,name=object_class,json=objectClass,proto3" json:"object_class,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRevisionByIdRequest) Reset() {
	*x = GetObjectRevisionByIdRequest{}
	mi := &file_proto_search_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRevisionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRevisionByIdRequest) ProtoMessage() {}

func (x *GetObjectRevisionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRevisionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRevisionByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetObjectRevisionByIdRequest) GetObjectClass() string {
	if x != nil {
		return x.ObjectClass
	}
	return ""
}

func (x *GetObjectRevisionByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetObjectRevisionByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *structpb.Value        `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRevisionByIdResponse) Reset() {
	*x = GetObjectRevisionByIdResponse{}
	mi := &file_proto_search_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRevisionByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRevisionByIdResponse) ProtoMessage() {}

func (x *GetObjectRevisionByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRevisionByIdResponse.ProtoReflect.Descriptor instead.
func (*GetObjectRevisionByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetObjectRevisionByIdResponse) GetContent() *structpb.Value {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetObjectByGlobalIdRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectRootClass string                 `protobuf:"bytes,1,opt,name=object_root_class,json=objectRootClass,proto3" json:"object_root_class,omitempty"`
	GlobalId        int64                  `protobuf:"varint,2,opt,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	DraftStatus     string                 `protobuf:"bytes,3,opt,name=draft_status,json=draftStatus,proto3" json:"draft_status,omitempty"`
	ActualDate      string                 `protobuf:"bytes,4,opt,name=actual_date,json=actualDate,proto3" json:"actual_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetObjectByGlobalIdRequest) Reset() {
	*x = GetObjectByGlobalIdRequest{}
	mi := &file_proto_search_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectByGlobalIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectByGlobalIdRequest) ProtoMessage() {}

func (x *GetObjectByGlobalIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectByGlobalIdRequest.ProtoReflect.Descriptor instead.
func (*GetObjectByGlobalIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjectByGlobalIdRequest) GetObjectRootClass() string {
	if x != nil {
		return x.ObjectRootClass
	}
	return ""
}

func (x *GetObjectByGlobalIdRequest) GetGlobalId() int64 {
	if x != nil {
		return x.GlobalId
	}
	return 0
}

func (x *GetObjectByGlobalIdRequest) GetDraftStatus() string {
	if x != nil {
		return x.DraftStatus
	}
	return ""
}

func (x *GetObjectByGlobalIdRequest) GetActualDate() string {
	if x != nil {
		return x.ActualDate
	}
	return ""
}

type GetObjectByGlobalIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *structpb.Value        `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectByGlobalIdResponse) Reset() {
	*x = GetObjectByGlobalIdResponse{}
	mi := &file_proto_search_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectByGlobalIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectByGlobalIdResponse) ProtoMessage() {}

func (x *GetObjectByGlobalIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectByGlobalIdResponse.ProtoReflect.Descriptor instead.
func (*GetObjectByGlobalIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetObjectByGlobalIdResponse) GetContent() *structpb.Value {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetObjectCollectionByParentIdRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectRootClass string                 `protobuf:"bytes,1,opt,name=object_root_class,json=objectRootClass,proto3" json:"object_root_class,omitempty"`
	ParentId        int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetObjectCollectionByParentIdRequest) Reset() {
	*x = GetObjectCollectionByParentIdRequest{}
	mi := &file_proto_search_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectCollectionByParentIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectCollectionByParentIdRequest) ProtoMessage() {}

func (x *GetObjectCollectionByParentIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectCollectionByParentIdRequest.ProtoReflect.Descriptor instead.
func (*GetObjectCollectionByParentIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetObjectCollectionByParentIdRequest) GetObjectRootClass() string {
	if x != nil {
		return x.ObjectRootClass
	}
	return ""
}

func (x *GetObjectCollectionByParentIdRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type GetObjectCollectionByParentIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*structpb.Value      `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectCollectionByParentIdResponse) Reset() {
	*x = GetObjectCollectionByParentIdResponse{}
	mi := &file_proto_search_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectCollectionByParentIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectCollectionByParentIdResponse) ProtoMessage() {}

func (x *GetObjectCollectionByParentIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectCollectionByParentIdResponse.ProtoReflect.Descriptor instead.
func (*GetObjectCollectionByParentIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetObjectCollectionByParentIdResponse) GetContents() []*structpb.Value {
	if x != nil {
		return x.Contents
	}
	return nil
}

type GetObjectGlobalIdByAltIdRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectRootClass string                 `protobuf:"bytes,1,opt,name=object_root_class,json=objectRootClass,proto3" json:"object_root_class,omitempty"`
	AltId           string                 `protobuf:"bytes,2,opt,name=alt_id,json=altId,proto3" json:"alt_id,omitempty"`
	SourceAlias     string                 `protobuf:"bytes,3,opt,name=source_alias,json=sourceAlias,proto3" json:"source_alias,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetObjectGlobalIdByAltIdRequest) Reset() {
	*x = GetObjectGlobalIdByAltIdRequest{}
	mi := &file_proto_search_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectGlobalIdByAltIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectGlobalIdByAltIdRequest) ProtoMessage() {}

func (x *GetObjectGlobalIdByAltIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectGlobalIdByAltIdRequest.ProtoReflect.Descriptor instead.
func (*GetObjectGlobalIdByAltIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetObjectGlobalIdByAltIdRequest) GetObjectRootClass() string {
	if x != nil {
		return x.ObjectRootClass
	}
	return ""
}

func (x *GetObjectGlobalIdByAltIdRequest) GetAltId() string {
	if x != nil {
		return x.AltId
	}
	return ""
}

func (x *GetObjectGlobalIdByAltIdRequest) GetSourceAlias() string {
	if x != nil {
		return x.SourceAlias
	}
	return ""
}

type GetObjectGlobalIdByAltIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalId      int64                  `protobuf:"varint,1,opt,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectGlobalIdByAltIdResponse) Reset() {
	*x = GetObjectGlobalIdByAltIdResponse{}
	mi := &file_proto_search_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectGlobalIdByAltIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectGlobalIdByAltIdResponse) ProtoMessage() {}

func (x *GetObjectGlobalIdByAltIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectGlobalIdByAltIdResponse.ProtoReflect.Descriptor instead.
func (*GetObjectGlobalIdByAltIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetObjectGlobalIdByAltIdResponse) GetGlobalId() int64 {
	if x != nil {
		return x.GlobalId
	}
	return 0
}

type GetObjectCollectionByFilterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectRootClass string                 `protobuf:"bytes,1,opt,name=object_root_class,json=objectRootClass,proto3" json:"object_root_class,omitempty"`
	DraftStatus     string                 `protobuf:"bytes,2,opt,name=draft_status,json=draftStatus,proto3" json:"draft_status,omitempty"`
	ActualDate      string                 `protobuf:"bytes,3,opt,name=actual_date,json=actualDate,proto3" json:"actual_date,omitempty"`
	Filter          *FilterExpr            `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort            []*SortField           `protobuf:"bytes,5,rep,name=sort,proto3" json:"sort,omitempty"`
	Limit           *wrapperspb.Int32Value `protobuf:"bytes,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          *wrapperspb.Int32Value `protobuf:"bytes,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetObjectCollectionByFilterRequest) Reset() {
	*x = GetObjectCollectionByFilterRequest{}
	mi := &file_proto_search_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectCollectionByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectCollectionByFilterRequest) ProtoMessage() {}

func (x *GetObjectCollectionByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectCollectionByFilterRequest.ProtoReflect.Descriptor instead.
func (*GetObjectCollectionByFilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetObjectCollectionByFilterRequest) GetObjectRootClass() string {
	if x != nil {
		return x.ObjectRootClass
	}
	return ""
}

func (x *GetObjectCollectionByFilterRequest) GetDraftStatus() string {
	if x != nil {
		return x.DraftStatus
	}
	return ""
}

func (x *GetObjectCollectionByFilterRequest) GetActualDate() string {
	if x != nil {
		return x.ActualDate
	}
	return ""
}

func (x *GetObjectCollectionByFilterRequest) GetFilter() *FilterExpr {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetObjectCollectionByFilterRequest) GetSort() []*SortField {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *GetObjectCollectionByFilterRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *GetObjectCollectionByFilterRequest) GetOffset() *wrapperspb.Int32Value {
	if x != nil {
		return x.Offset
	}
	return nil
}

type GetObjectCollectionByFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*structpb.Value      `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectCollectionByFilterResponse) Reset() {
	*x = GetObjectCollectionByFilterResponse{}
	mi := &file_proto_search_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectCollectionByFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectCollectionByFilterResponse) ProtoMessage() {}

func (x *GetObjectCollectionByFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectCollectionByFilterResponse.ProtoReflect.Descriptor instead.
func (*GetObjectCollectionByFilterResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetObjectCollectionByFilterResponse) GetContents() []*structpb.Value {
	if x != nil {
		return x.Contents
	}
	return nil
}

type SortField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction     SortDirection          `protobuf:"varint,2,opt,name=direction,proto3,enum=searchservice.SortDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortField) Reset() {
	*x = SortField{}
	mi := &file_proto_search_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortField) ProtoMessage() {}

func (x *SortField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortField.ProtoReflect.Descriptor instead.
func (*SortField) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{10}
}

func (x *SortField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortField) GetDirection() SortDirection {
	if x != nil {
		return x.Direction
	}
	return SortDirection_SORT_DIRECTION_UNSPECIFIED
}

type FilterExpr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Expr:
	//
	//	*FilterExpr_And
	//	*FilterExpr_Or
	//	*FilterExpr_Not
	//	*FilterExpr_Predicate
	Expr          isFilterExpr_Expr `protobuf_oneof:"expr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterExpr) Reset() {
	*x = FilterExpr{}
	mi := &file_proto_search_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterExpr) ProtoMessage() {}

func (x *FilterExpr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterExpr.ProtoReflect.Descriptor instead.
func (*FilterExpr) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{11}
}

func (x *FilterExpr) GetExpr() isFilterExpr_Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *FilterExpr) GetAnd() *FilterAnd {
	if x != nil {
		if x, ok := x.Expr.(*FilterExpr_And); ok {
			return x.And
		}
	}
	return nil
}

func (x *FilterExpr) GetOr() *FilterOr {
	if x != nil {
		if x, ok := x.Expr.(*FilterExpr_Or); ok {
			return x.Or
		}
	}
	return nil
}

func (x *FilterExpr) GetNot() *FilterNot {
	if x != nil {
		if x, ok := x.Expr.(*FilterExpr_Not); ok {
			return x.Not
		}
	}
	return nil
}

func (x *FilterExpr) GetPredicate() *FilterPredicate {
	if x != nil {
		if x, ok := x.Expr.(*FilterExpr_Predicate); ok {
			return x.Predicate
		}
	}
	return nil
}

type isFilterExpr_Expr interface {
	isFilterExpr_Expr()
}

type FilterExpr_And struct {
	And *FilterAnd `protobuf:"bytes,1,opt,name=and,proto3,oneof"`
}

type FilterExpr_Or struct {
	Or *FilterOr `protobuf:"bytes,2,opt,name=or,proto3,oneof"`
}

type FilterExpr_Not struct {
	Not *FilterNot `protobuf:"bytes,3,opt,name=not,proto3,oneof"`
}

type FilterExpr_Predicate struct {
	Predicate *FilterPredicate `protobuf:"bytes,4,opt,name=predicate,proto3,oneof"`
}

func (*FilterExpr_And) isFilterExpr_Expr() {}

func (*FilterExpr_Or) isFilterExpr_Expr() {}

func (*FilterExpr_Not) isFilterExpr_Expr() {}

func (*FilterExpr_Predicate) isFilterExpr_Expr() {}

type FilterAnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*FilterExpr          `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterAnd) Reset() {
	*x = FilterAnd{}
	mi := &file_proto_search_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterAnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterAnd) ProtoMessage() {}

func (x *FilterAnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterAnd.ProtoReflect.Descriptor instead.
func (*FilterAnd) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{12}
}

func (x *FilterAnd) GetChildren() []*FilterExpr {
	if x != nil {
		return x.Children
	}
	return nil
}

type FilterOr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*FilterExpr          `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterOr) Reset() {
	*x = FilterOr{}
	mi := &file_proto_search_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterOr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterOr) ProtoMessage() {}

func (x *FilterOr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterOr.ProtoReflect.Descriptor instead.
func (*FilterOr) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{13}
}

func (x *FilterOr) GetChildren() []*FilterExpr {
	if x != nil {
		return x.Children
	}
	return nil
}

type FilterNot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Child         *FilterExpr            `protobuf:"bytes,1,opt,name=child,proto3" json:"child,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterNot) Reset() {
	*x = FilterNot{}
	mi := &file_proto_search_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterNot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterNot) ProtoMessage() {}

func (x *FilterNot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterNot.ProtoReflect.Descriptor instead.
func (*FilterNot) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{14}
}

func (x *FilterNot) GetChild() *FilterExpr {
	if x != nil {
		return x.Child
	}
	return nil
}

type FilterPredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      FilterOperator         `protobuf:"varint,2,opt,name=operator,proto3,enum=searchservice.FilterOperator" json:"operator,omitempty"`
	Values        []*FilterValue         `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterPredicate) Reset() {
	*x = FilterPredicate{}
	mi := &file_proto_search_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterPredicate) ProtoMessage() {}

func (x *FilterPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterPredicate.ProtoReflect.Descriptor instead.
func (*FilterPredicate) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{15}
}

func (x *FilterPredicate) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FilterPredicate) GetOperator() FilterOperator {
	if x != nil {
		return x.Operator
	}
	return FilterOperator_FILTER_OPERATOR_UNSPECIFIED
}

func (x *FilterPredicate) GetValues() []*FilterValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type FilterValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*FilterValue_StringValue
	//	*FilterValue_Int64Value
	//	*FilterValue_Int32Value
	//	*FilterValue_DoubleValue
	//	*FilterValue_BoolValue
	//	*FilterValue_DateValue
	//	*FilterValue_DatetimeValue
	Kind          isFilterValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterValue) Reset() {
	*x = FilterValue{}
	mi := &file_proto_search_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterValue) ProtoMessage() {}

func (x *FilterValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterValue.ProtoReflect.Descriptor instead.
func (*FilterValue) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{16}
}

func (x *FilterValue) GetKind() isFilterValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *FilterValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*FilterValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FilterValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*FilterValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *FilterValue) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Kind.(*FilterValue_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *FilterValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*FilterValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *FilterValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*FilterValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *FilterValue) GetDateValue() string {
	if x != nil {
		if x, ok := x.Kind.(*FilterValue_DateValue); ok {
			return x.DateValue
		}
	}
	return ""
}

func (x *FilterValue) GetDatetimeValue() string {
	if x != nil {
		if x, ok := x.Kind.(*FilterValue_DatetimeValue); ok {
			return x.DatetimeValue
		}
	}
	return ""
}

type isFilterValue_Kind interface {
	isFilterValue_Kind()
}

type FilterValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FilterValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type FilterValue_Int32Value struct {
	Int32Value int32 `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type FilterValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type FilterValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type FilterValue_DateValue struct {
	DateValue string `protobuf:"bytes,6,opt,name=date_value,json=dateValue,proto3,oneof"`
}

type FilterValue_DatetimeValue struct {
	DatetimeValue string `protobuf:"bytes,7,opt,name=datetime_value,json=datetimeValue,proto3,oneof"`
}

func (*FilterValue_StringValue) isFilterValue_Kind() {}

func (*FilterValue_Int64Value) isFilterValue_Kind() {}

func (*FilterValue_Int32Value) isFilterValue_Kind() {}

func (*FilterValue_DoubleValue) isFilterValue_Kind() {}

func (*FilterValue_BoolValue) isFilterValue_Kind() {}

func (*FilterValue_DateValue) isFilterValue_Kind() {}

func (*FilterValue_DatetimeValue) isFilterValue_Kind() {}

type GetDomainConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainConfigRequest) Reset() {
	*x = GetDomainConfigRequest{}
	mi := &file_proto_search_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainConfigRequest) ProtoMessage() {}

func (x *GetDomainConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainConfigRequest.ProtoReflect.Descriptor instead.
func (*GetDomainConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{17}
}

type GetDomainConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	LoadedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=loaded_at,json=loadedAt,proto3" json:"loaded_at,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,5,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainConfigResponse) Reset() {
	*x = GetDomainConfigResponse{}
	mi := &file_proto_search_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainConfigResponse) ProtoMessage() {}

func (x *GetDomainConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainConfigResponse.ProtoReflect.Descriptor instead.
func (*GetDomainConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetDomainConfigResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetDomainConfigResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetDomainConfigResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetDomainConfigResponse) GetLoadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LoadedAt
	}
	return nil
}

func (x *GetDomainConfigResponse) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

var File_proto_search_service_proto protoreflect.FileDescriptor

const file_proto_search_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/search_service.proto\x12\rsearchservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"Q\n" +
	"\x1cGetObjectRevisionByIdRequest\x12!\n" +
	"\fobject_class\x18\x01 \x01(\tR\vobjectClass\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"Q\n" +
	"\x1dGetObjectRevisionByIdResponse\x120\n" +
	"\acontent\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\acontent\"\xa9\x01\n" +
	"\x1aGetObjectByGlobalIdRequest\x12*\n" +
	"\x11object_root_class\x18\x01 \x01(\tR\x0fobjectRootClass\x12\x1b\n" +
	"\tglobal_id\x18\x02 \x01(\x03R\bglobalId\x12!\n" +
	"\fdraft_status\x18\x03 \x01(\tR\vdraftStatus\x12\x1f\n" +
	"\vactual_date\x18\x04 \x01(\tR\n" +
	"actualDate\"O\n" +
	"\x1bGetObjectByGlobalIdResponse\x120\n" +
	"\acontent\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\acontent\"o\n" +
	"$GetObjectCollectionByParentIdRequest\x12*\n" +
	"\x11object_root_class\x18\x01 \x01(\tR\x0fobjectRootClass\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\"[\n" +
	"%GetObjectCollectionByParentIdResponse\x122\n" +
	"\bcontents\x18\x01 \x03(\v2\x16.google.protobuf.ValueR\bcontents\"\x87\x01\n" +
	"\x1fGetObjectGlobalIdByAltIdRequest\x12*\n" +
	"\x11object_root_class\x18\x01 \x01(\tR\x0fobjectRootClass\x12\x15\n" +
	"\x06alt_id\x18\x02 \x01(\tR\x05altId\x12!\n" +
	"\fsource_alias\x18\x03 \x01(\tR\vsourceAlias\"?\n" +
	" GetObjectGlobalIdByAltIdResponse\x12\x1b\n" +
	"\tglobal_id\x18\x01 \x01(\x03R\bglobalId\"\xdd\x02\n" +
	"\"GetObjectCollectionByFilterRequest\x12*\n" +
	"\x11object_root_class\x18\x01 \x01(\tR\x0fobjectRootClass\x12!\n" +
	"\fdraft_status\x18\x02 \x01(\tR\vdraftStatus\x12\x1f\n" +
	"\vactual_date\x18\x03 \x01(\tR\n" +
	"actualDate\x121\n" +
	"\x06filter\x18\x04 \x01(\v2\x19.searchservice.FilterExprR\x06filter\x12,\n" +
	"\x04sort\x18\x05 \x03(\v2\x18.searchservice.SortFieldR\x04sort\x121\n" +
	"\x05limit\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x123\n" +
	"\x06offset\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\x06offset\"Y\n" +
	"#GetObjectCollectionByFilterResponse\x122\n" +
	"\bcontents\x18\x01 \x03(\v2\x16.google.protobuf.ValueR\bcontents\"]\n" +
	"\tSortField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12:\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x1c.searchservice.SortDirectionR\tdirection\"\xdb\x01\n" +
	"\n" +
	"FilterExpr\x12,\n" +
	"\x03and\x18\x01 \x01(\v2\x18.searchservice.FilterAndH\x00R\x03and\x12)\n" +
	"\x02or\x18\x02 \x01(\v2\x17.searchservice.FilterOrH\x00R\x02or\x12,\n" +
	"\x03not\x18\x03 \x01(\v2\x18.searchservice.FilterNotH\x00R\x03not\x12>\n" +
	"\tpredicate\x18\x04 \x01(\v2\x1e.searchservice.FilterPredicateH\x00R\tpredicateB\x06\n" +
	"\x04expr\"B\n" +
	"\tFilterAnd\x125\n" +
	"\bchildren\x18\x01 \x03(\v2\x19.searchservice.FilterExprR\bchildren\"A\n" +
	"\bFilterOr\x125\n" +
	"\bchildren\x18\x01 \x03(\v2\x19.searchservice.FilterExprR\bchildren\"<\n" +
	"\tFilterNot\x12/\n" +
	"\x05child\x18\x01 \x01(\v2\x19.searchservice.FilterExprR\x05child\"\x96\x01\n" +
	"\x0fFilterPredicate\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x129\n" +
	"\boperator\x18\x02 \x01(\x0e2\x1d.searchservice.FilterOperatorR\boperator\x122\n" +
	"\x06values\x18\x03 \x03(\v2\x1a.searchservice.FilterValueR\x06values\"\x90\x02\n" +
	"\vFilterValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12!\n" +
	"\vint32_value\x18\x03 \x01(\x05H\x00R\n" +
	"int32Value\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"date_value\x18\x06 \x01(\tH\x00R\tdateValue\x12'\n" +
	"\x0edatetime_value\x18\a \x01(\tH\x00R\rdatetimeValueB\x06\n" +
	"\x04kind\"\x18\n" +
	"\x16GetDomainConfigRequest\"\xbb\x01\n" +
	"\x17GetDomainConfigResponse\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x127\n" +
	"\tloaded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bloadedAt\x12\x1f\n" +
	"\vconfig_json\x18\x05 \x01(\tR\n" +
	"configJson*`\n" +
	"\rSortDirection\x12\x1e\n" +
	"\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SORT_DIRECTION_ASC\x10\x01\x12\x17\n" +
	"\x13SORT_DIRECTION_DESC\x10\x02*\xcd\x02\n" +
	"\x0eFilterOperator\x12\x1f\n" +
	"\x1bFILTER_OPERATOR_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FILTER_OPERATOR_EQ\x10\x01\x12\x16\n" +
	"\x12FILTER_OPERATOR_NE\x10\x02\x12\x16\n" +
	"\x12FILTER_OPERATOR_GT\x10\x03\x12\x16\n" +
	"\x12FILTER_OPERATOR_GE\x10\x04\x12\x16\n" +
	"\x12FILTER_OPERATOR_LT\x10\x05\x12\x16\n" +
	"\x12FILTER_OPERATOR_LE\x10\x06\x12\x16\n" +
	"\x12FILTER_OPERATOR_IN\x10\a\x12\x1a\n" +
	"\x16FILTER_OPERATOR_NOT_IN\x10\b\x12\x18\n" +
	"\x14FILTER_OPERATOR_LIKE\x10\t\x12\x1b\n" +
	"\x17FILTER_OPERATOR_IS_NULL\x10\n" +
	"\x12\x1f\n" +
	"\x1bFILTER_OPERATOR_IS_NOT_NULL\x10\v2\xe4\x05\n" +
	"\rSearchService\x12r\n" +
	"\x15GetObjectRevisionById\x12+.searchservice.GetObjectRevisionByIdRequest\x1a,.searchservice.GetObjectRevisionByIdResponse\x12l\n" +
	"\x13GetObjectByGlobalId\x12).searchservice.GetObjectByGlobalIdRequest\x1a*.searchservice.GetObjectByGlobalIdResponse\x12\x8a\x01\n" +
	"\x1dGetObjectCollectionByParentId\x123.searchservice.GetObjectCollectionByParentIdRequest\x1a4.searchservice.GetObjectCollectionByParentIdResponse\x12{\n" +
	"\x18GetObjectGlobalIdByAltId\x12..searchservice.GetObjectGlobalIdByAltIdRequest\x1a/.searchservice.GetObjectGlobalIdByAltIdResponse\x12\x84\x01\n" +
	"\x1bGetObjectCollectionByFilter\x121.searchservice.GetObjectCollectionByFilterRequest\x1a2.searchservice.GetObjectCollectionByFilterResponse\x12`\n" +
	"\x0fGetDomainConfig\x12%.searchservice.GetDomainConfigRequest\x1a&.searchservice.GetDomainConfigResponseB8Z6github.com/quantara/search-service/proto;searchserviceb\x06proto3"

var (
	file_proto_search_service_proto_rawDescOnce sync.Once
	file_proto_search_service_proto_rawDescData []byte
)

func file_proto_search_service_proto_rawDescGZIP() []byte {
	file_proto_search_service_proto_rawDescOnce.Do(func() {
		file_proto_search_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_service_proto_rawDesc), len(file_proto_search_service_proto_rawDesc)))
	})
	return file_proto_search_service_proto_rawDescData
}

var file_proto_search_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_search_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_search_service_proto_goTypes = []any{
	(SortDirection)(0),                            // 0: searchservice.SortDirection
	(FilterOperator)(0),                           // 1: searchservice.FilterOperator
	(*GetObjectRevisionByIdRequest)(nil),          // 2: searchservice.GetObjectRevisionByIdRequest
	(*GetObjectRevisionByIdResponse)(nil),         // 3: searchservice.GetObjectRevisionByIdResponse
	(*GetObjectByGlobalIdRequest)(nil),            // 4: searchservice.GetObjectByGlobalIdRequest
	(*GetObjectByGlobalIdResponse)(nil),           // 5: searchservice.GetObjectByGlobalIdResponse
	(*GetObjectCollectionByParentIdRequest)(nil),  // 6: searchservice.GetObjectCollectionByParentIdRequest
	(*GetObjectCollectionByParentIdResponse)(nil), // 7: searchservice.GetObjectCollectionByParentIdResponse
	(*GetObjectGlobalIdByAltIdRequest)(nil),       // 8: searchservice.GetObjectGlobalIdByAltIdRequest
	(*GetObjectGlobalIdByAltIdResponse)(nil),      // 9: searchservice.GetObjectGlobalIdByAltIdResponse
	(*GetObjectCollectionByFilterRequest)(nil),    // 10: searchservice.GetObjectCollectionByFilterRequest
	(*GetObjectCollectionByFilterResponse)(nil),   // 11: searchservice.GetObjectCollectionByFilterResponse
	(*SortField)(nil),                             // 12: searchservice.SortField
	(*FilterExpr)(nil),                            // 13: searchservice.FilterExpr
	(*FilterAnd)(nil),                             // 14: searchservice.FilterAnd
	(*FilterOr)(nil),                              // 15: searchservice.FilterOr
	(*FilterNot)(nil),                             // 16: searchservice.FilterNot
	(*FilterPredicate)(nil),                       // 17: searchservice.FilterPredicate
	(*FilterValue)(nil),                           // 18: searchservice.FilterValue
	(*GetDomainConfigRequest)(nil),                // 19: searchservice.GetDomainConfigRequest
	(*GetDomainConfigResponse)(nil),               // 20: searchservice.GetDomainConfigResponse
	(*structpb.Value)(nil),                        // 21: google.protobuf.Value
	(*wrapperspb.Int32Value)(nil),                 // 22: google.protobuf.Int32Value
	(*timestamppb.Timestamp)(nil),                 // 23: google.protobuf.Timestamp
}
var file_proto_search_service_proto_depIdxs = []int32{
	21, // 0: searchservice.GetObjectRevisionByIdResponse.content:type_name -> google.protobuf.Value
	21, // 1: searchservice.GetObjectByGlobalIdResponse.content:type_name -> google.protobuf.Value
	21, // 2: searchservice.GetObjectCollectionByParentIdResponse.contents:type_name -> google.protobuf.Value
	13, // 3: searchservice.GetObjectCollectionByFilterRequest.filter:type_name -> searchservice.FilterExpr
	12, // 4: searchservice.GetObjectCollectionByFilterRequest.sort:type_name -> searchservice.SortField
	22, // 5: searchservice.GetObjectCollectionByFilterRequest.limit:type_name -> google.protobuf.Int32Value
	22, // 6: searchservice.GetObjectCollectionByFilterRequest.offset:type_name -> google.protobuf.Int32Value
	21, // 7: searchservice.GetObjectCollectionByFilterResponse.contents:type_name -> google.protobuf.Value
	0,  // 8: searchservice.SortField.direction:type_name -> searchservice.SortDirection
	14, // 9: searchservice.FilterExpr.and:type_name -> searchservice.FilterAnd
	15, // 10: searchservice.FilterExpr.or:type_name -> searchservice.FilterOr
	16, // 11: searchservice.FilterExpr.not:type_name -> searchservice.FilterNot
	17, // 12: searchservice.FilterExpr.predicate:type_name -> searchservice.FilterPredicate
	13, // 13: searchservice.FilterAnd.children:type_name -> searchservice.FilterExpr
	13, // 14: searchservice.FilterOr.children:type_name -> searchservice.FilterExpr
	13, // 15: searchservice.FilterNot.child:type_name -> searchservice.FilterExpr
	1,  // 16: searchservice.FilterPredicate.operator:type_name -> searchservice.FilterOperator
	18, // 17: searchservice.FilterPredicate.values:type_name -> searchservice.FilterValue
	23, // 18: searchservice.GetDomainConfigResponse.loaded_at:type_name -> google.protobuf.Timestamp
	2,  // 19: searchservice.SearchService.GetObjectRevisionById:input_type -> searchservice.GetObjectRevisionByIdRequest
	4,  // 20: searchservice.SearchService.GetObjectByGlobalId:input_type -> searchservice.GetObjectByGlobalIdRequest
	6,  // 21: searchservice.SearchService.GetObjectCollectionByParentId:input_type -> searchservice.GetObjectCollectionByParentIdRequest
	8,  // 22: searchservice.SearchService.GetObjectGlobalIdByAltId:input_type -> searchservice.GetObjectGlobalIdByAltIdRequest
	10, // 23: searchservice.SearchService.GetObjectCollectionByFilter:input_type -> searchservice.GetObjectCollectionByFilterRequest
	19, // 24: searchservice.SearchService.GetDomainConfig:input_type -> searchservice.GetDomainConfigRequest
	3,  // 25: searchservice.SearchService.GetObjectRevisionById:output_type -> searchservice.GetObjectRevisionByIdResponse
	5,  // 26: searchservice.SearchService.GetObjectByGlobalId:output_type -> searchservice.GetObjectByGlobalIdResponse
	7,  // 27: searchservice.SearchService.GetObjectCollectionByParentId:output_type -> searchservice.GetObjectCollectionByParentIdResponse
	9,  // 28: searchservice.SearchService.GetObjectGlobalIdByAltId:output_type -> searchservice.GetObjectGlobalIdByAltIdResponse
	11, // 29: searchservice.SearchService.GetObjectCollectionByFilter:output_type -> searchservice.GetObjectCollectionByFilterResponse
	20, // 30: searchservice.SearchService.GetDomainConfig:output_type -> searchservice.GetDomainConfigResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_search_service_proto_init() }
func file_proto_search_service_proto_init() {
	if File_proto_search_service_proto != nil {
		return
	}
	file_proto_search_service_proto_msgTypes[11].OneofWrappers = []any{
		(*FilterExpr_And)(nil),
		(*FilterExpr_Or)(nil),
		(*FilterExpr_Not)(nil),
		(*FilterExpr_Predicate)(nil),
	}
	file_proto_search_service_proto_msgTypes[16].OneofWrappers = []any{
		(*FilterValue_StringValue)(nil),
		(*FilterValue_Int64Value)(nil),
		(*FilterValue_Int32Value)(nil),
		(*FilterValue_DoubleValue)(nil),
		(*FilterValue_BoolValue)(nil),
		(*FilterValue_DateValue)(nil),
		(*FilterValue_DatetimeValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_service_proto_rawDesc), len(file_proto_search_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_service_proto_goTypes,
		DependencyIndexes: file_proto_search_service_proto_depIdxs,
		EnumInfos:         file_proto_search_service_proto_enumTypes,
		MessageInfos:      file_proto_search_service_proto_msgTypes,
	}.Build()
	File_proto_search_service_proto = out.File
	file_proto_search_service_proto_goTypes = nil
	file_proto_search_service_proto_depIdxs = nil
}
